name: dub unit tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    name: dlang-unit-test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        dcompiler: [dmd-latest, ldc-latest]

    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install BLAS (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install libopenblas-dev

      - name: Install BLAS (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install openblas
          brew link openblas
      
#       - name: Install chocolatey windows
#         if: matrix.os == 'windows-latest'
#         uses: crazy-max/ghaction-chocolatey@v1.6.0

#       - name: Install BLAS (Windows)
#         if: matrix.os == 'windows-latest'
#         run: |
#           choco install openblas -y

      - name: Install D Compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dcompiler }}

      - name: Run tests and build coverage
        run: dub test -q --build=unittest-cov --parallel
        
      - name: Code Coverage
        uses: codecov/codecov-action@v2

